### ISSUE TITLE
Windows icon

### ISSUE THREAD

**Issue by nthnchu** [rayyansaidi-com/app#2]
Can't figure out how to convert to windows .ico correctly. Electron builder does this automatically from the .png, but we should make an ico soon...

https://github.com/rayyansaidi-com/app/runs/885664432?check_suite_focus=true#step:5:103

```
Error while loading icon from "D:\a\app\app\app-master\app-master\build\icon.ico": invalid icon file size
```

**Comment by MrSun10** [comment]
OK
I don't know what you are talking about.

**Comment by nthnchu** [comment]
Closed as electron builder does it itself, so we don't need to currently
