### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by Ryyn-Sd** [rayyansaidi-com/app#5]
Can you do it so as you resize the window by height, the sidebar’s height, and the text on the sidebar will get smaller?

**Comment by nthnchu** [comment]
Yeah this should be easy enough but we have to have a point where the sidebar just cuts off. An alternate solution would just be to cut off the window size at a certain point, so the user can't make it that small. Your choice @Ryyn-Sd.

**Comment by Ryyn-Sd** [comment]
OK. I'll do
>just be to cut off the window size at a certain point, so the user can't make it that small.

**Comment by nthnchu** [comment]
I already did that with you.

```js
minWidth: 500,
minHeight: 600,
```

**Comment by nthnchu** [comment]
Fixed in 4dd86f6ead5e888012bbe643b76c2ba57c91c26b
