### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Ryyn-Sd** [rayyansaidi-com/app#8]
Can you add React to this app?

**Comment by nthnchu** [comment]
What would we do with it though? Why do you want this @Ryyn-Sd?

**Comment by Ryyn-Sd** [comment]
That will come when we know what we can do with react.

Since we can do everything with HTML, CSS, and javascript, I think that we shouldn't do it.

**Comment by nthnchu** [comment]
> That will come when we know what we can do with react.
> 
> Since we can do everything with HTML, CSS, and javascript, I think that we shouldn't do it.

Ok kinda what I thought. Vanilla JS is always faster :D

**Comment by Ryyn-Sd** [comment]
Ya
