### ISSUE TITLE
Screenshot button on small devices

### ISSUE THREAD

**Issue by Ryyn-Sd** [rayyansaidi-com/app#9]
If the window size is smaller then 768 px, but larger then 610 px, and I scroll down to the bottom, the screenshot button won't show

**Comment by nthnchu** [comment]
Why is this closed @Ryyn-Sd? Not resolved at all!

**Comment by Ryyn-Sd** [comment]
Because I fixed it.

**Comment by Ryyn-Sd** [comment]
By not allowing holiday templates to show past 768 pixels, which is when it switches into mobile mode.
